version: '3.9'
services:
  backend-db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: quypham
      MYSQL_PASSWORD: Abc123456
      MYSQL_DATABASE: backend-db
    expose:
      - "3306"


  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_container
    environment:
      DATABASE_HOST: backend-db
      DATABASE_PORT: 3306
      DATABASE_USER: quypham
      DATABASE_PASSWORD: password
      DATABASE_NAME: your_database_name
    ports:
      - "3001:3001"
    depends_on:
      - backend-db